-- 기존 테이블이 있다면 삭제 (테스트 환경용)
-- DROP TABLE IF EXISTS notifications;
-- DROP TABLE IF EXISTS attendance;
-- DROP TABLE IF EXISTS students;

-- 학생 테이블
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  parent TEXT NOT NULL,
  phone TEXT NOT NULL,
  belt TEXT NOT NULL DEFAULT '흰띠',
  active BOOLEAN NOT NULL DEFAULT true,
  fcm_token TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 초기 샘플 데이터
INSERT INTO students (number, name, age, parent, phone, belt, active)
VALUES 
  ('01', '김태권', 8, '김철수', '010-1234-5678', '흰띠', true),
  ('02', '이도복', 10, '이영희', '010-2345-6789', '노란띠', true),
  ('03', '박겨루', 9, '박민수', '010-3456-7890', '초록띠', true),
  ('04', '최발차', 11, '최지은', '010-4567-8901', '파란띠', true),
  ('05', '정품새', 7, '정호준', '010-5678-9012', '흰띠', true),
  ('06', '강태극', 12, '강수연', '010-6789-0123', '빨간띠', true)
ON CONFLICT (number) DO NOTHING;

-- 출석 기록 테이블
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  student_name TEXT NOT NULL,
  number TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('등원', '하원')),
  time TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 알림 기록 테이블
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  student_name TEXT NOT NULL,
  parent_name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('등원', '하원')),
  time TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Realtime 활성화를 위해 각 테이블의 REPLICA IDENTITY를 설정
ALTER PUBLICATION supabase_realtime ADD TABLE students;
ALTER PUBLICATION supabase_realtime ADD TABLE attendance;
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;

-- (선택) RLS(Row Level Security) 설정 (개발 편의를 위해 일단 모두 허용)
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read access" ON students FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert access" ON students FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous update access" ON students FOR UPDATE TO anon USING (true);

CREATE POLICY "Allow anonymous read access" ON attendance FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert access" ON attendance FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow anonymous read access" ON notifications FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert access" ON notifications FOR INSERT TO anon WITH CHECK (true);
